-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPTB4nR+KwkoNk50z
G0WdFZANlqb8fmCC7nOO8v1agaKgCgYIKoZIzj0DAQehRANCAAQpfOkHOSQ270SU
FiiFK1hLGaSf4rPwM936PjKYVGHedXKxHLXiaUmKLlFddjXRa5gZA4IJwpgcRlKK
BaQwz6Wd
-----END PRIVATE KEY-----