// grab the things we need
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

// create a schema
var settingSchema = new Schema({
	call_us:String,
	support_email: String,
	fb_url: String,
	twitter_url: String,
	instagram_url: String,
	pinterest_url: String,
	youtube_url: String,
	linkedin_url: String,
	app_name: String,
	default_name: String,
	default_email: String,
	admin_email: String,
	default_footer: String,
	google_playstore: String,
	apple_store: String,
	fetch_deduct_percentage: String,
	currency: String,
	stripe_live_key: String,
	stripe_test_key: String,
	stripe_status: String,
	twilio_account_sid: String,
	twilio_auth_token: String,
	twilio_mobile_no: String,
	twilio_twiml_app_sid: String,
	twilio_caller_id: String,
	mailgun_api_key: String,
	mailgun_domain: String,
	key_id_ios: String,
	team_id_ios: String,
	bundle_id_csutomer: String,
	bundle_id_driver: String,
	ios_push_notification: String,
	android_server_key: String,
	driver_trip_radius: String,
	wallet_discount: String,
	panic_customer_number: String,
	sos_customer_number: String,
	address: String,
	invite_friend_commission: Number,
	schedule_trip_time: Number,
	consumer_trip_time_out: Number,
	cancel_trip_timer: Number,
	trip_timer: Number,
	driver_offline_time : Number,
	time_formate: String,
	android_version_code_user: String,
	android_version_code_driver: String,
	ios_version_code_user: String,
	ios_version_code_driver: String,
	is_stripe_payment_live: { type: Boolean, default: false },
	is_cash: { type: Boolean, default: false },
	is_wallet: { type: Boolean, default: false },
	is_stripe: { type: Boolean, default: false },
	is_wave: { type: Boolean, default: false },
	is_cash_out: { type: Boolean, default: false },
	is_production:{ type: Boolean, default: false },
	is_subscription:{ type: Boolean, default: false },
});

var Setting = mongoose.model('Setting', settingSchema);
module.exports = Setting;